name: cicd with actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # - name: Build the stack
      #   run: docker compose --env-file .env up
      - name: 'Create env file'
        run: |
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env
          echo DEV_HOST=${{ secrets.DEV_HOST }} >> .env
          echo PROD_HOST_DB=${{ secrets.PROD_HOST_DB }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT=5432 }} >> .env
          echo PROD_HOST_REDIS=${{ secrets.PROD_HOST_REDIS }} >> .env
          echo REDIS_PORT=${{ secrets.REDIS_PORT }} >> .env
          echo MAIL_USER=${{ secrets.MAIL_USER }} >> .env
          echo MAIL_TOKEN=${{ secrets.MAIL_TOKEN }} >> .env
          echo TG_TOKEN=${{ secrets.TG_TOKEN }} >> .env
          cat .env
      - name: install modules
        run: npm install
      - name: start project
        run: npm run start
      - name: unit test
        run: npm run test:unit
      - name: e2e test
        run: npm run test:integration
